# Generated by Django 5.0.6 on 2024-05-24 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
   initial = True

   dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
   ]

   operations = [
      migrations.CreateModel(
         name='ConfirmMailToken',
         fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('token_key', models.CharField(max_length=100, unique=True)),
            ('token_key_expires', models.DateTimeField(blank=True, null=True)),
            ('last_sent_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                          related_name='confirm_mail_token', to=settings.AUTH_USER_MODEL)),
         ],
         options={
            'verbose_name': 'Confirm Mail Token',
            'verbose_name_plural': 'Confirm Mail Tokens',
         },
      ),
      migrations.CreateModel(
         name='ForgotPasswordToken',
         fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('token_key', models.CharField(max_length=100, unique=True)),
            ('token_key_expires', models.DateTimeField(blank=True, null=True)),
            ('last_sent_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ('user',
             models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_password_token',
                                  to=settings.AUTH_USER_MODEL)),
         ],
         options={
            'abstract': False,
         },
      ),
      migrations.CreateModel(
         name='ForgotUsernameToken',
         fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('token_key', models.CharField(max_length=100, unique=True)),
            ('token_key_expires', models.DateTimeField(blank=True, null=True)),
            ('last_sent_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ('user',
             models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_email_token',
                                  to=settings.AUTH_USER_MODEL)),
         ],
         options={
            'abstract': False,
         },
      ),
      migrations.CreateModel(
         name='Status',
         fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('is_confirmed', models.BooleanField(default=False)),
            ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                        to='authentication.confirmmailtoken')),
            ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
         ],
         options={
            'verbose_name': 'Status',
            'verbose_name_plural': 'Status',
         },
      ),
   ]
