# Generated by Django 5.0.6 on 2024-05-24 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
   initial = True

   dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
   ]

   operations = [
      migrations.CreateModel(
         name='TodoItem',
         fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('title', models.CharField(max_length=100)),
            ('completed', models.BooleanField(default=False)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
         ],
      ),
   ]
