# Generated by Django 5.0.6 on 2024-06-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
   dependencies = [
      ('todo', '0001_initial'),
   ]

   operations = [
      migrations.RemoveField(
         model_name='todoitem',
         name='completed',
      ),
      migrations.AddField(
         model_name='todoitem',
         name='completed_at',
         field=models.DateTimeField(blank=True, null=True),
      ),
      migrations.AddField(
         model_name='todoitem',
         name='will_complete_at',
         field=models.DateTimeField(blank=True, null=True),
      ),
   ]
